<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3QS3pZQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3QS3pZQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3QS3pZQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3QS3pZQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3QS3pZQ\App_KernelDevDebugContainer([
    'container.build_hash' => '3QS3pZQ',
    'container.build_id' => '47ac593b',
    'container.build_time' => 1687920665,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3QS3pZQ');
